apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  channel: hal-9000
  username: "HAL-9000"
  secretRef:
    name: discord-webhook
