name: conftest
on: [pull_request]
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Run Kubernetes tools
        uses: stefanprodan/kube-tools@v1
        with:
          conftest: 0.18.2
          command: |
            echo "Run conftest"
            conftest test apps/
            echo "Run kubeval"
            kubeval -d apps/
